# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_led.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(277, 127)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbLED1On = QtWidgets.QPushButton(self.centralwidget)
        self.pbLED1On.setGeometry(QtCore.QRect(50, 70, 81, 31))
        self.pbLED1On.setObjectName("pbLED1On")
        self.pbLED2On = QtWidgets.QPushButton(self.centralwidget)
        self.pbLED2On.setGeometry(QtCore.QRect(160, 70, 71, 31))
        self.pbLED2On.setObjectName("pbLED2On")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Led Control"))
        self.pbLED1On.setText(_translate("MainWindow", "LED 1 ON"))
        self.pbLED2On.setText(_translate("MainWindow", "LED 2 ON"))
        self.label.setText(_translate("MainWindow", "LED 1"))
        self.label_2.setText(_translate("MainWindow", "LED2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
