# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_serial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cboPort = QtWidgets.QComboBox(self.centralwidget)
        self.cboPort.setGeometry(QtCore.QRect(80, 40, 151, 22))
        self.cboPort.setObjectName("cboPort")
        self.cboBaud = QtWidgets.QComboBox(self.centralwidget)
        self.cboBaud.setGeometry(QtCore.QRect(310, 40, 141, 22))
        self.cboBaud.setObjectName("cboBaud")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 40, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(230, 80, 241, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.btnLed1On = QtWidgets.QPushButton(self.centralwidget)
        self.btnLed1On.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.btnLed1On.setObjectName("btnLed1On")
        self.btnLED2On = QtWidgets.QPushButton(self.centralwidget)
        self.btnLED2On.setGeometry(QtCore.QRect(130, 100, 75, 23))
        self.btnLED2On.setObjectName("btnLED2On")
        self.lblSw = QtWidgets.QLabel(self.centralwidget)
        self.lblSw.setGeometry(QtCore.QRect(70, 170, 128, 128))
        self.lblSw.setText("")
        self.lblSw.setObjectName("lblSw")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Port"))
        self.label_2.setText(_translate("MainWindow", "Baud"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.pushButton_2.setText(_translate("MainWindow", "Disconnect"))
        self.btnLed1On.setText(_translate("MainWindow", "LED1 On"))
        self.btnLED2On.setText(_translate("MainWindow", "LED2 On"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
